dependencies:
- name: angular-io-quickstart
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.5
- name: eks-demo
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.4
- alias: expose
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.82
- alias: cleanup
  name: exposecontroller
  repository: http://chartmuseum.jenkins-x.io
  version: 2.3.82
- name: golang-template
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.22
- name: golang-template-http
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.12
- name: golang-web
  repository: http://jenkins-x-chartmuseum:8080
  version: 0.0.8
